language: php

php:
  - 5.3
  - 5.4
  - 5.5
  - 5.6
  - hhvm

matrix:
  allow_failures:
    - hhvm

branches:
  only:
    - master
    - develop

before_script:
  - curl -s https://getcomposer.org/installer | php
  - $(which php) composer.phar --dev install
  - git --version
  - git config --global user.email "test@travis-ci.org"
  - git config --global user.name "Travis"
  - git --version

script:
  - vendor/bin/phpunit
  
