secure: "nJsRdCK/Qi50fwrAt67mu+GBzWrw+h+6G0lyzyTHXOWuUtK8fuO9fDWlsEOO\nOshiX1KYDysYDud/6WRdkMOP1cU5DH2dZgMVNMXaMFG+zPGMjHD361/k9qt0\ngnFXBrwl8vKg9/Xx0soBRmMaID8Iuib8NLIxTNPZfYW1So/5Vgo="

language: php

php:
  - 5.3
  - 5.4
  - 5.5

matrix:
  allow_failures:
    - php: 5.5

branches:
  only:
    - master
    - develop

before_script:
  - curl -s https://getcomposer.org/installer | php
  - php composer.phar --dev install
  - git config --global user.email "test@travis-ci.org"
  - git config --global user.name "Travis"
  - mkdir ~/.composer
  - echo '{ "config": { "github-oauth": { "github.com": "<%= ENV['KEY'] %>" } } }' > ~/.composer/config.json

script:
  - vendor/bin/phpunit --coverage-clover "clover"

after_success:
  - curl -sL https://bit.ly/artifact-uploader | php
  
