language: php
phps:
  - 5.3
  - 5.4
branches:
  only:
    - master
    - develop

before_script:
  - curl -s https://getcomposer.org/installer | php
  - php composer.phar --dev install

script:
  - vendor/bin/phpunit --coverage-clover "clover"

after_success:
  - curl -sL https://bit.ly/artifact-uploader | php
  
