language: php
phps:
  - 5.3
  - 5.4
branches:
  only:
    - master
    - develop

before_script:
  - wget -nc http://getcomposer.org/composer.phar
  - php composer.phar install
  - wget https://github.com/downloads/Behat/Behat/behat.phar

script:
  - php behat.phar
  - phpunit
  
